language: node_js
node_js:
  - '4.2'

env:
  global:
  - secure: ZDBwe+pnZ1n87+kVy2Dde3cPqJ4id/QFeRRPIIsz8uBETTDqF/wqNMQYslVdQWvWu6lLzyb8WAAwaCujldRMdmO5oKw18CuLC/hEMXB0OLoSxedPromfS2W1G9MfyxYeSJn4JxMGv/GQYQ3DFM+Gb8mvinWpo9YQfhm0GUIeZdBRgnEEjApbtRilH/etyB6p1qdX1t1bawM7rrGma0DUrlTvSGF09Vl1fdHc4MIzrqp23B5fmoKbQISsA/6lcVL/VgU4TTAXXc0Htj7L4cMtNMuJwWfQZ3M0gyZjI4fEfylr9YFTbweNbpUdKcryrNV3QTE416HlaKwXwIBJNewKZbDYn+5y81gmlboalOJ+9XF6ItqofYD/bkSyN0BlH4gXZqWojueOE/Kuethudy/ktVquWB6aMgYYIkjiqM4gwmV9LC6BcsOheleKLOsjoS2rMwwbq1n826j3Kf3tmcgzrsE0wtaCRGhGiqBqhkBNtYPc+R9vJ01DOeUmArKoj9sGyoHpNIRiIt5BimUkDgKIG4PG98FQHDxjvqx0a8euE/6rhC/W/v3ZSnVX/JJZfSJfnnqZYWqiqbnjz7Y3+2O1C4hsPE/GUdkZQRerGauiW5UcGegqctl0chANy9RLVilet6g0mLEt+tjPuFkBd7axkG3w3fvmRy6rjgpJ1Xn/YdY=
  - secure: cY7ppNhBmZy41rCjQXJ2CV0vha4h1AzUO2IlRVkN3c3AC4ZnSEeiYUQLNGdiktVPO1oUTFxuM9e0BY4y8OPCVJAYOZiMfhNSwYOUMh4nnbSZiMMxeSZT5Q9zqt9fZewwQq09pbLR5IEV2wGu7UFH7yBUBQUuGQyN3JY1GWO0dLWaMWDO6Q6YksVxhZLY3YO6QyUiER9ONk+I+KcHIofEtIOOKFeYScjOuav9ZnEb5v0lvPxDSgJI4AeCA3SSuRsiseJ3aoYNejyZQzrTJwgA7aN4//mJEpg922j7zoZgI9H2rXRFvtYqiQ9pDew0XJt45p8t25+6kiYEyH5SRGQMoKDvKQR4rKGdJR/vYyUoJTMTzZu7xiM9VjpegGOQ296etgIaUCYjnGM7PvNWA6yzmW2mdiEjtfRTKJpbo9vSRGdb0UK28ep2KpDZTddPubRQOR6K7R1QJ9xSfuA18KcICGCNdO4ENAlSE6TmlMBz9y/RzNKy+vk5Hlz/Gr7rLuuQfSFvsz3w+rpmXVsfw3FhWKyieYlbIpdr7PGx8S76YgTa0oEl9uDmnzely4Nz1iGABs8qpznGHWL2VbYne/No+/I4YtpYhF38QQBoyctBKdeeaTv+I7O8XTO5WSqc1oeapYQr8JJ81aqKkQtlHIwlH+QNIatcxBB9pGhjmZvIY8k=
  - secure: N0JJAVo+bqnFJcqKT5Te4VHpdMCzGEcF5hSV2k967p83PyCZ1Cy2x64xA/cLlXdJeYLHEDd9rpeNpxCHXP6kLQom7ftlMk/l09WEF+LnVUPvZ6ROrNHMu+5KI/0N1XAPHnmLHpmc9ptGjvuKTK94LwQmVNgMT+k6wmP55JP263z55KnjwChXmq8/S8/X6NcrKJrhFvGayJ0Pytv0hifH1irX6+53alg2Tk+bpLfjwHG/t2P4uM7uDqGU0gjdC8ilaawB/Fp/h9y7skjxKXPn3KchXb3fYPB1UnMmRt+UhpbhdqHvx9wQ+XG7nudawO+/Z7YxC3l0MuTVzEa9aOMLm+Fy9dQp9O29lz7sZd8G0LcCjYh2PTPXX9BUulj+tj/tuxv8BaGWOAXIkOfITYJb1WqF6tuZ0UL4I4ky1kPz5fKQSh+kcvCGF7yNXD0L/wq9wPWdFqgbHtnU+j3bxdeEftf19drfAkaaoTnoUTgLtVRvO63UJMDDwjqt+mcyHhQSU4PjMpuOC0DDp/maa1siuh12fqOM1htG69hOO362cuCzMP7ZohWsu4j4C8fdxuEjvPqhVQTKU+yvEZnaWWHvu5gEMWqXuw5kapblK7Xp2CsCYPUaA6/1a/ZZd7oKTIT9E1815GQ5pnybw6gWsVdlYKKf9QRGLBIP+/dXiLsdJ8w=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
